spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mimidai?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
      maxActive: 50
      maxIdle: 5
      minIdle: 0
      initialSize: 0
      filters: stat,wall,log4j
      validation-query: select 1
      test-on-borrow: true
#--------------------------------
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mimidai?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: root
      maxActive: 50
      maxIdle: 5
      minIdle: 0
      initialSize: 0
      validation-query: select 1
      test-on-borrow: true
#--------------------------------
  redis:
    host: 192.168.1.65
    port: 6380
    password:
    jedis:
      pool:
        max-active: 800
        max-idle: 200
        min-idle: 20
        max-wait: 10000
logging:
  file: D:/logs/cms.log
  level.root: info

switch:
  isSendPush: true
  isSendMessage: false
