spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.62:3306/mimidai?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
      password: iMPm7NtlZrtC5jLSquczmzyzIsRM5a0HgDu6TWoPQwe75txV1knjsYxbdaM2a3zNOz0pmWnYL8O0vyic1jseqQ==
      maxActive: 50
      maxIdle: 5
      minIdle: 0
      initialSize: 0
      filters: stat,wall,log4j
      validation-query: select 1
      test-on-borrow: true
    #--------------------------------
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.108:3306/mimidai_1904?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
      password: TYviITPes4cKXB5V58LKZ/e9ki8B0rxwjrauOUF/FfV7efnMpjp1+Yeb8zXX3pDU2Qox69lQKYF5oxI56WsmFA==
      maxActive: 50
      maxIdle: 5
      minIdle: 0
      initialSize: 0
      validation-query: select 1
      test-on-borrow: true
  #--------------------------------
  redis:
    host: 192.168.1.65
    port: 6380
    password:
    jedis:
      pool:
        max-active: 800
        max-idle: 200
        min-idle: 20
        max-wait: 10000
#--------------------------------
switch:
   isSendPush: true
   isSendMessage: false

logging:
  file: D:/logs/cms.log
  level.root: info

