server:
  port: 8763
spring:
  application:
    name: feign

eureka:
  instance:
    prefer-ip-address: true
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8081/eureka/
#开启熔断器
feign:
  hystrix:
    enabled: true
